f1 = open("col_visited", 'w')
f2 = open("col_paths", 'w')
f3 = open("parsed_list", 'w')
f4 = open("neighbors", 'w')
f5 = open("out", 'w')

f1.write("")
f2.write("")
f3.write("")
f4.write("")
f5.write("")

f1.close()
f2.close()
f3.close()
f4.close()
f5.close()
